add install llvm action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,11 +49,15 @@ jobs:
         run: |
             ${{matrix.setenvs}}
             src/build-scripts/ci-startup.bash
-      - name: Install curl
+      - name: Install 7-zip
         shell: bash
         run: |
             VCPKG_INSTALLATION_ROOT=/c/vcpkg
             vcpkg install 7zip
+      - name: Add 7-Zip to PATH
+        run: |
+            echo "##[add-path]C:/vcpkg/installed/x64-windows/bin"
+            7z --version || echo "7z command not found. Check installation."
       # choco install 7zip.install
       # - name: Install Flex and Bison
       #   shell: bash
